### PR TITLE
Fix installNewIndex with ELS 2.X (Close and open Index between putSettings)

### PR DESCRIPTION
**Pull request by obigroup**
Fix installNewIndex with ELS 2.X (Close and open Index between putSettings)

### CODE REVIEW

**Comment by afoucret** [comment]
There is a little more work than this close and open tricks to provide ES 2.x compatibility (mostly the migration from facets to aggregations).

For now we do not provide ES 2.x compatibility but it will change in few days since I have a private version under test. You should stay in 2.x for few more days.

I will not merge this one because it is already in my private repo.

**Comment by obigroup** [comment]
Do you have a release date for the 2.x version ?

Thank you.

**Comment by afoucret** [comment]
I expect it will happened next week or the next one.

**Comment by obigroup** [comment]
Hello @afoucret,

Do you have some news about the next version ?

Thx.

**Comment by simbus82** [comment]
HI @afoucret, thanks for this great work!
In our server we have ES 2.x, and i receive always the same error about the "facet" problem.

How i can do a workaround to "not use facets" in Magento CE 1.9.2.2 or let your module not give me this error?

Can i disable this thing in some place? Thanks

**Comment by obigroup** [comment]
Hello @afoucret,

Do you have some news about the next version ?

Thx.

**Comment by simbus82** [comment]
We see a bounch of updates some day ago. Are there something about ES 2.x? Thanks

**Pull request closed without merging**
