### PR TITLE
Fix issue on ES 2.x with putSettings

### PR DESCRIPTION
**Pull request by sylvainraye**
Fix issue error "Can't update non dynamic settings", close the index, add the setting and reopen it

### CODE REVIEW

**Comment by romainruaud** [comment]
Hello @diglin and thanks for the PR.

However, I see you are using ES 2.x. The module is not compatible with this version of ES since all search filters are built using facets instead of aggregations so you may experience many other issues linked to an ES 2.x compatibility.

Regards,

**Comment by sylvainraye** [comment]
Yes right, it was the case indeed. But I thought it may help you if you wish to support ES 2.x.

**Comment by romainruaud** [comment]
Hello @diglin but sorry, the ES 2.x support is not on our roadmap for this module. The explanation is quite simple, this is due to the fact that we should rewrite all the filter part to move from facets to aggregation. We do not plan to spend such time since Magento2 is released and our module for M2 has also been published.

Regards,

**Comment by sylvainraye** [comment]
ok right, it makes sense.

**Pull request closed without merging**
